name: Publish to npm registry
run-name: Publishing {{ github.event.release.tag_name }} to npm registry

release:
  types: [published]

jobs:
  release:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies 
        run: pnpm install --frozen-lockfile

      - name: Set version to release tag
        shell: bash
        run: pnpm version from-git --no-commit-hooks --no-git-tag-version --allow-same-version

      - name: Bump version and publish to npm registry
        shell: bash
        run: pnpm publish --access public -r
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_SECRET }}

      - name: Push version changes to main branch
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: release ${{ github.event.release.tag_name }}"
          branch: ${{ github.event.repository.default_branch }}
          file_pattern: package.json